### ISSUE TITLE
Writing more than one Word

### ISSUE THREAD

**Issue by vale5566** [CodeDesignInitiative/code-sign#7]
When i write more than one word like [this.]( https://screenshots.firefox.com/Iuc86TABFJXmWtCW/cdcamp.de)
Come this error: There was a critical error executing your request. The form was not valid.

Maybe the maximum size of the picture?

**Comment by fronbasal** [comment]
Fixed with commit 4b18027b28f698e5579ca8ba7e41a949db0639c1.
